Добавил поддержку свойства привязка к файлу
maximaster/tools.orm pull request #16
Opened 2019-02-25 19:10 UTC by 111ypuk

Добавил поддержку свойства привязка к файлу с референсов на этот таблицу FileTable

2019-02-26 09:08 UTC, mmjurov requested changes
Спасибо за PR! Оставил несколько небольших замечаний. После исправления потестирую, если все ок - то волью в master

2019-02-26 09:08 UTC, mmjurov commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                            \Bitrix\Iblock\PropertyEnumerationTable::class,
В composer.json заявлена совместимость с php 5.3. Эта возможность появилась только в php 5.5

2019-02-26 09:08 UTC, mmjurov commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                           $valueReference = array(
Тут с переносами непорядок. Нужно выровнять

2019-02-26 09:08 UTC, mmjurov commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                            \Bitrix\Main\FileTable::class,
это для php 5.5+. У нас же совместимость с php 5.3+

2019-02-26 09:33 UTC, 111ypuk commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                            \Bitrix\Iblock\PropertyEnumerationTable::class,
поправил

2019-03-04 19:54 UTC, 111ypuk commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                           $valueReference = array(
поправил

2019-03-04 19:55 UTC, 111ypuk commented on src/Maximaster/Tools/Orm/Iblock/ElementTable.php
> +                            \Bitrix\Main\FileTable::class,
gjghfdbk

2019-03-12 20:20 UTC, merged

2019-03-12 20:20 UTC, mmjurov commented
Спасибо!